### PR TITLE
Bump Flux dependency to latest (v0.12.3)

### PR DESCRIPTION
**Pull request by AlexLewandowski**
This is enough to get the example in the README working and is a very minor fix. I don't know Zygote well enough to understand why the grads have `Main.x` and `Main.y` variables of type `GlobalRef`, but I have excluded them because they cause errors in veclength.

### CODE REVIEW

**Comment by baggepinnen** [comment]
Thanks for having a look at this! I tried running the tests locally, not sure why they didn't run here (tried to close/open this PR to trigger them..), but they failed rather Immediately. 

I have not really maintained this package lately since there is supposed to be built-in functionality replacing the `copyto` in this package. Have you seen https://github.com/baggepinnen/FluxOptTools.jl/issues/4 ?
I've never used the built-in functionality, but if it works, maybe we should update to use that instead of reimplementing it here.

**Comment by AlexLewandowski** [comment]
The tests related to FluxOptTools pass, at least on my end. Zygote can't handle the `x` variable from `LinRange`, it needs to be collected: `x = collect(LinRange(-pi,pi,100)')` which fixes the broadcasting error.

I did not know about `Flux.destructure` though, that does provide a stable API in case things change within Flux.

**Comment by baggepinnen** [comment]
I pushed an update to use GH actions, apparently this repo still had travis set up (which is no longer working).

**Comment by baggepinnen** [comment]
Thank you for your PR :)

**Pull request merged**
